import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [{
      rel: 'icon',
      sizes: 'any',
      url: 'favicon.ico',
  }]
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-beige-100 font-nunito text-beige-900 text-sm'>{children}</body>
    </html>
  )
}
